apiVersion: v1
kind: Service
metadata:
  labels:
    category: web
    challenge: nginxed
  name: nginxed-web-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
      clientIP:
          timeoutSeconds: 3600
  ports:
    - name: "nginxed-web"
      port: 80
      targetPort: 1337
  selector:
    category: web
    challenge: nginxed
