apiVersion: v1
kind: Service
metadata:
  labels:
    category: web
    challenge: nginxed
  name: nginxed-web-service
spec:
  type: NodePort
  ports:
  - name: "nginxed-nodeport"
    port: 1337
    targetPort: 1337
    nodePort: 30102
  selector:
    category: web
    challenge: nginxed
