apiVersion: v1
kind: Service
metadata:
  name: fanboy-web-service
spec:
  type: NodePort
  ports:
  - name: "fanboy-nodeport"
    port: 1337
    targetPort: 1337
    nodePort: 30107
  selector:
    category: forensics
    challenge: fanboy
