apiVersion: v1
kind: Service
metadata:
  name: multi-stage-crypto-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
      clientIP:
          timeoutSeconds: 3600
  ports:
    - name: "web"
      port: 80
      targetPort: 8000
  selector:
    category: crypto
    challenge: multi-stage-crypto
