apiVersion: v1
kind: Service
metadata:
  name: multi-stage-crypto-web-service
spec:
  type: NodePort
  ports:
  - name: "multi-stage-crypto-nodeport"
    port: 1337
    targetPort: 1337
    nodePort: 30105
  selector:
    category: crypto
    challenge: multi-stage-crypto
