apiVersion: v1
kind: Service
metadata:
  name: decrypt-dev-tcp-service
spec:
  type: NodePort
  ports:
  - name: "decrypt-dev-nodeport"
    port: 1337
    targetPort: 1337
    nodePort: 30202
  selector:
    category: crypto
    challenge: decrypt-dev
