apiVersion: v1
kind: Service
metadata:
  labels:
    category: web
    challenge: jwt1
  name: jwt2-web-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
      clientIP:
          timeoutSeconds: 3600
  ports:
    - name: "jwt2-web"
      port: 80
      targetPort: 1337
  selector:
    category: web
    challenge: jwt2
