apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    category: pwn
    challenge: mqu-rpg
  name: mqu-rpg 
spec:
  replicas: 1
  selector:
    matchLabels:
      category: pwn
      challenge: mqu-rpg
  template:
    metadata:
      labels:
        category: pwn
        challenge: mqu-rpg
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: mqu-rpg
        image: gcr.io/hackmac-challenges-2020-13337/mqu-rpg:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          privileged: true
        ports:
        - containerPort: 1337
          name: port-1337
