apiVersion: v1
kind: Service
metadata:
  name: mqu-rpg-tcp-service
spec:
  type: NodePort
  ports:
  - name: "mqu-rpg-nodeport"
    port: 1337
    targetPort: 1337
    nodePort: 30001
  selector:
    category: pwn
    challenge: mqu-rpg
