apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    category: crypto
    challenge: zoom-zoom
  name: zoom-zoom
spec:
  replicas: 1
  selector:
    matchLabels:
      category: crypto
      challenge: zoom-zoom
  template:
    metadata:
      labels:
        category: crypto
        challenge: zoom-zoom
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: zoom-zoom
        image: gcr.io/hackmac-challenges-2020-13337/zoom-zoom:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          privileged: true
        ports:
        - containerPort: 1337
          name: port-1337
