apiVersion: v1
kind: Service
metadata:
  name: zoom-zoom
  labels:
    category: crypto
    challenge: zoom-zoom
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
      clientIP:
          timeoutSeconds: 3600
  ports:
    - name: "zoom-zoom-port"
      port: 1337
      targetPort: 1337
  selector:
    category: crypto
    challenge: zoom-zoom
    