apiVersion: v1
kind: Service
metadata:
  name: zoom-zoom-tcp-service
spec:
  type: NodePort
  ports:
  - name: "zoom-zoom-nodeport"
    port: 1337
    targetPort: 1337
    nodePort: 30201
  selector:
    category: crypto
    challenge: zoom-zoom
