apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: jwt1-web-service
spec:
  type: NodePort
  ports:
  - name: "jwt1-nodeport"
    port: 1337
    targetPort: 1337
    nodePort: 30103
  selector:
    category: web
    challenge: jwt1
