version: "3"

services:
  web:
    build:
      context: .
    restart: unless-stopped
    environment:
      - "MYSQL_HOST=db"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=adjfhufhwuihejhfwhqfouwhohf"
      - "MYSQL_DB=logindetails"
      - "WORKER_PORT=8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_DATABASE=logindetails"
      - "MYSQL_ROOT_PASSWORD=adjfhufhwuihejhfwhqfouwhohf"
