apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sticky-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "2"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "2"

spec:
  rules:
  - host: "this-seems-familiar.chal.hackmac.xyz"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            serviceName: web-service
            servicePort: 30000
      - path: /
        pathType: Prefix
        backend:
            serviceName: web-service
            servicePort: 30001
