apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    category: rev
    challenge: ok-boomer
  name: ok-boomer 
spec:
  replicas: 1
  selector:
    matchLabels:
      category: rev
      challenge: ok-boomer
  template:
    metadata:
      labels:
        category: rev
        challenge: ok-boomer
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: ok-boomer
        image: gcr.io/hackmac-challenges-2020-13337/ok-boomer:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 250m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          privileged: true
        ports:
        - containerPort: 1337
          name: port-1337
